// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  username: __t.string().primaryKey(),
  identityHex: __t.string().name("identity_hex"),
  saltB64: __t.string().name("salt_b64"),
  nonceB64: __t.string().name("nonce_b64"),
  cipherB64: __t.string().name("cipher_b64"),
  createdAt: __t.timestamp().name("created_at"),
});
