// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  arenaId: __t.i32().name("arena_id"),
  seq: __t.i32(),
  attackerId: __t.i32().name("attacker_id"),
  targetId: __t.i32().name("target_id"),
  attackerSourceUnitId: __t.i32().name("attacker_source_unit_id"),
  targetSourceUnitId: __t.i32().name("target_source_unit_id"),
  damage: __t.i32(),
  targetKilled: __t.bool().name("target_killed"),
  action: __t.i32(),
  destX: __t.i32().name("dest_x"),
  destY: __t.i32().name("dest_y"),
});
