// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  arenaId: __t.i32().name("arena_id"),
  sourceUnitId: __t.i32().name("source_unit_id"),
  ownerId: __t.string().name("owner_id"),
  team: __t.string(),
  currentHealth: __t.i32().name("current_health"),
  maxHealth: __t.i32().name("max_health"),
  attack: __t.i32(),
  defense: __t.i32(),
  speed: __t.i32(),
  isAlive: __t.bool().name("is_alive"),
  positionX: __t.f32().name("position_x"),
  positionY: __t.f32().name("position_y"),
});
