// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  roomId: __t.i32().name("room_id"),
  roundNumber: __t.i32().name("round_number"),
  status: __t.string(),
  turnNumber: __t.i32().name("turn_number"),
  winnerTeam: __t.option(__t.string()).name("winner_team"),
  createdAt: __t.timestamp().name("created_at"),
  nextActorIndex: __t.i32().name("next_actor_index"),
});
