// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.string(),
  name: __t.string(),
  creatorId: __t.string(),
  buyinAmount: __t.f64(),
  votesPerPlayer: __t.i32(),
  minPlayers: __t.i32(),
  maxPlayers: __t.i32(),
  allowRebuy: __t.bool(),
  allowMidgameJoin: __t.bool(),
};
