// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type DirectMessageConversation = {
  id: string,
  user1: Identity,
  user2: Identity,
  lastMessageAt: bigint,
  createdAt: bigint,
};

/**
 * A namespace for generated helper functions.
 */
export namespace DirectMessageConversation {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createStringType()),
      new ProductTypeElement("user1", AlgebraicType.createIdentityType()),
      new ProductTypeElement("user2", AlgebraicType.createIdentityType()),
      new ProductTypeElement("lastMessageAt", AlgebraicType.createI64Type()),
      new ProductTypeElement("createdAt", AlgebraicType.createI64Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: DirectMessageConversation): void {
    DirectMessageConversation.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): DirectMessageConversation {
    return DirectMessageConversation.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


