// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type GameRoom = {
  id: number,
  name: string,
  memberIds: string[],
  ticketIds: string[],
  offerIds: string[],
  startTime: bigint | undefined,
  currentRound: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameRoom {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("memberIds", AlgebraicType.createArrayType(AlgebraicType.createStringType())),
      new ProductTypeElement("ticketIds", AlgebraicType.createArrayType(AlgebraicType.createStringType())),
      new ProductTypeElement("offerIds", AlgebraicType.createArrayType(AlgebraicType.createStringType())),
      new ProductTypeElement("startTime", AlgebraicType.createOptionType(AlgebraicType.createI64Type())),
      new ProductTypeElement("currentRound", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameRoom): void {
    GameRoom.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameRoom {
    return GameRoom.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


