// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  memberIds: __t.array(__t.string()).name("member_ids"),
  ticketIds: __t.array(__t.string()).name("ticket_ids"),
  offerIds: __t.array(__t.string()).name("offer_ids"),
  startTime: __t.option(__t.i64()).name("start_time"),
  currentRound: __t.i32().name("current_round"),
  buyinAmount: __t.f64().name("buyin_amount"),
  potSize: __t.f64().name("pot_size"),
  roundDuration: __t.i32().name("round_duration"),
  gameStatus: __t.string().name("game_status"),
  eliminatedPlayers: __t.array(__t.string()).name("eliminated_players"),
  votesPerPlayer: __t.i32().name("votes_per_player"),
  minPlayers: __t.i32().name("min_players"),
  maxPlayers: __t.option(__t.i32()).name("max_players"),
  allowRebuy: __t.bool().name("allow_rebuy"),
  allowMidgameJoin: __t.bool().name("allow_midgame_join"),
});
