// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  roomId: __t.i32().name("room_id"),
  roundNumber: __t.i32().name("round_number"),
  voteId: __t.i32().name("vote_id"),
  sellerId: __t.string().name("seller_id"),
  color: __t.string(),
  price: __t.f64(),
  guaranteeType: __t.string().name("guarantee_type"),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.timestamp().name("created_at"),
});
