// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  unitId: __t.i32().primaryKey().name("unit_id"),
  generation: __t.i32(),
  parentAId: __t.option(__t.i32()).name("parent_a_id"),
  parentBId: __t.option(__t.i32()).name("parent_b_id"),
  combatIv: __t.i32().name("combat_iv"),
  gatheringIv: __t.i32().name("gathering_iv"),
  craftingIv: __t.i32().name("crafting_iv"),
  speedIv: __t.i32().name("speed_iv"),
  healthIv: __t.i32().name("health_iv"),
  staminaIv: __t.i32().name("stamina_iv"),
});
