// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  ownerId: __t.string().name("owner_id"),
  laborerId: __t.i32().name("laborer_id"),
  equipmentType: __t.string().name("equipment_type"),
  slot: __t.string(),
  itemName: __t.string().name("item_name"),
  tier: __t.i32(),
  material: __t.string(),
  enchantment: __t.option(__t.string()),
  quality: __t.string(),
  surface: __t.string(),
  attackBonus: __t.i32().name("attack_bonus"),
  defenseBonus: __t.i32().name("defense_bonus"),
  speedBonus: __t.i32().name("speed_bonus"),
  healthBonus: __t.i32().name("health_bonus"),
  durability: __t.i32(),
  maxDurability: __t.i32().name("max_durability"),
});
