// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  ownerId: __t.string().name("owner_id"),
  displayName: __t.string().name("display_name"),
  origin: __t.string(),
  woodcuttingXp: __t.i32().name("woodcutting_xp"),
  woodcuttingLevel: __t.i32().name("woodcutting_level"),
  miningXp: __t.i32().name("mining_xp"),
  miningLevel: __t.i32().name("mining_level"),
  foragingXp: __t.i32().name("foraging_xp"),
  foragingLevel: __t.i32().name("foraging_level"),
  craftingXp: __t.i32().name("crafting_xp"),
  craftingLevel: __t.i32().name("crafting_level"),
  sourceRoomId: __t.i32().name("source_room_id"),
  health: __t.i32(),
  maxHealth: __t.i32().name("max_health"),
  attack: __t.i32(),
  defense: __t.i32(),
  speed: __t.i32(),
});
