// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  identity: __t.identity(),
  roomId: __t.i32().name("room_id"),
  x: __t.f32(),
  z: __t.f32(),
  rotationY: __t.f32().name("rotation_y"),
  isMoving: __t.bool().name("is_moving"),
});
