// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type QueueUnitTask = {
  unitId: number,
  taskType: string,
  targetId: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace QueueUnitTask {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("unitId", AlgebraicType.createI32Type()),
      new ProductTypeElement("taskType", AlgebraicType.createStringType()),
      new ProductTypeElement("targetId", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: QueueUnitTask): void {
    QueueUnitTask.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): QueueUnitTask {
    return QueueUnitTask.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

