// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ReadyState } from "./ready_state_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `ready_state`.
 *
 * Obtain a handle from the [`readyState`] property on [`RemoteTables`],
 * like `ctx.db.readyState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.readyState.on_insert(...)`.
 */
export class ReadyStateTableHandle {
  tableCache: TableCache<ReadyState>;

  constructor(tableCache: TableCache<ReadyState>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ReadyState> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `roomId` unique index on the table `ready_state`,
   * which allows point queries on the field of the same name
   * via the [`ReadyStateRoomIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.readyState.roomId().find(...)`.
   *
   * Get a handle on the `roomId` unique index on the table `ready_state`.
   */
  roomId = {
    // Find the subscribed row whose `roomId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): ReadyState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.roomId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ReadyState) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ReadyState) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ReadyState) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ReadyState) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ReadyState, newRow: ReadyState) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ReadyState, newRow: ReadyState) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
