// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vector2,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.i32().name("room_id"),
  resourceType: __t.string().name("resource_type"),
  get position() {
    return Vector2;
  },
  amount: __t.i32(),
  maxAmount: __t.i32().name("max_amount"),
  regenerationRate: __t.i32().name("regeneration_rate"),
  regenerationTimer: __t.i32().name("regeneration_timer"),
  depletionThreshold: __t.i32().name("depletion_threshold"),
});
