// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  serverType: __t.string().name("server_type"),
  parentId: __t.option(__t.i32()).name("parent_id"),
  tradingPeriodSeconds: __t.i64().name("trading_period_seconds"),
  status: __t.string(),
  linkedRoomId: __t.option(__t.i32()).name("linked_room_id"),
  createdAt: __t.timestamp().name("created_at"),
});
