// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  roomId: __t.i32().name("room_id"),
  roundNumber: __t.i32().name("round_number"),
  bettorId: __t.string().name("bettor_id"),
  betType: __t.string().name("bet_type"),
  betTarget: __t.string().name("bet_target"),
  amount: __t.f64(),
  payoutMultiplier: __t.f64().name("payout_multiplier"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
