// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  entryFee: __t.f64().name("entry_fee"),
  prizePool: __t.f64().name("prize_pool"),
  maxParticipants: __t.i32().name("max_participants"),
  currentRound: __t.i32().name("current_round"),
  status: __t.string(),
  bracketType: __t.string().name("bracket_type"),
  roomIds: __t.array(__t.i32()).name("room_ids"),
  participantIds: __t.array(__t.string()).name("participant_ids"),
  createdAt: __t.timestamp().name("created_at"),
});
