// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  roomId: __t.i32().name("room_id"),
  roundNumber: __t.i32().name("round_number"),
  fromPlayer: __t.string().name("from_player"),
  offerType: __t.string().name("offer_type"),
  voteId: __t.option(__t.i32()).name("vote_id"),
  price: __t.f64(),
  status: __t.string(),
  acceptedBy: __t.option(__t.string()).name("accepted_by"),
  createdAt: __t.timestamp().name("created_at"),
});
