// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  roomId: __t.i32().name("room_id"),
  fromPlayer: __t.string().name("from_player"),
  toPlayer: __t.string().name("to_player"),
  transactionType: __t.string().name("transaction_type"),
  amount: __t.f64(),
  voteId: __t.option(__t.i32()).name("vote_id"),
  guaranteeId: __t.option(__t.i32()).name("guarantee_id"),
  timestamp: __t.timestamp(),
});
