// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Transaction = {
  id: number,
  roomId: number,
  fromPlayer: string,
  toPlayer: string,
  transactionType: string,
  amount: number,
  voteId: number | undefined,
  guaranteeId: number | undefined,
  timestamp: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Transaction {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("roomId", AlgebraicType.createI32Type()),
      new ProductTypeElement("fromPlayer", AlgebraicType.createStringType()),
      new ProductTypeElement("toPlayer", AlgebraicType.createStringType()),
      new ProductTypeElement("transactionType", AlgebraicType.createStringType()),
      new ProductTypeElement("amount", AlgebraicType.createF64Type()),
      new ProductTypeElement("voteId", AlgebraicType.createOptionType(AlgebraicType.createI32Type())),
      new ProductTypeElement("guaranteeId", AlgebraicType.createOptionType(AlgebraicType.createI32Type())),
      new ProductTypeElement("timestamp", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Transaction): void {
    Transaction.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Transaction {
    return Transaction.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


