// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountBind = __t.object("AccountBind", {
  username: __t.string(),
  identityHex: __t.string(),
  saltB64: __t.string(),
  nonceB64: __t.string(),
  cipherB64: __t.string(),
  createdAt: __t.timestamp(),
});
export type AccountBind = __Infer<typeof AccountBind>;

export const BattleArena = __t.object("BattleArena", {
  id: __t.i32(),
  roomId: __t.i32(),
  roundNumber: __t.i32(),
  status: __t.string(),
  turnNumber: __t.i32(),
  winnerTeam: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  nextActorIndex: __t.i32(),
});
export type BattleArena = __Infer<typeof BattleArena>;

export const BattleCombatEvent = __t.object("BattleCombatEvent", {
  id: __t.i32(),
  arenaId: __t.i32(),
  seq: __t.i32(),
  attackerId: __t.i32(),
  targetId: __t.i32(),
  attackerSourceUnitId: __t.i32(),
  targetSourceUnitId: __t.i32(),
  damage: __t.i32(),
  targetKilled: __t.bool(),
  action: __t.i32(),
  destX: __t.i32(),
  destY: __t.i32(),
});
export type BattleCombatEvent = __Infer<typeof BattleCombatEvent>;

export const BattleTurnTimer = __t.object("BattleTurnTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  arenaId: __t.i32(),
});
export type BattleTurnTimer = __Infer<typeof BattleTurnTimer>;

export const BattleUnit = __t.object("BattleUnit", {
  id: __t.i32(),
  arenaId: __t.i32(),
  sourceUnitId: __t.i32(),
  ownerId: __t.string(),
  team: __t.string(),
  currentHealth: __t.i32(),
  maxHealth: __t.i32(),
  attack: __t.i32(),
  defense: __t.i32(),
  speed: __t.i32(),
  isAlive: __t.bool(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  spawnX: __t.f32(),
  spawnY: __t.f32(),
});
export type BattleUnit = __Infer<typeof BattleUnit>;

export const BlockedUser = __t.object("BlockedUser", {
  id: __t.i32(),
  blocker: __t.identity(),
  blocked: __t.identity(),
  createdAt: __t.timestamp(),
});
export type BlockedUser = __Infer<typeof BlockedUser>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.string(),
  roomId: __t.string(),
  sender: __t.identity(),
  text: __t.string(),
  timestamp: __t.timestamp(),
  roundNumber: __t.option(__t.i32()),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChatPermission = __t.object("ChatPermission", {
  id: __t.i32(),
  roomId: __t.string(),
  userId: __t.identity(),
  permission: __t.string(),
});
export type ChatPermission = __Infer<typeof ChatPermission>;

export const ChatRoom = __t.object("ChatRoom", {
  id: __t.string(),
  name: __t.string(),
  createdAt: __t.i64(),
  creatorId: __t.string(),
});
export type ChatRoom = __Infer<typeof ChatRoom>;

export const DirectMessage = __t.object("DirectMessage", {
  id: __t.i32(),
  conversationId: __t.string(),
  sender: __t.identity(),
  text: __t.string(),
  timestamp: __t.timestamp(),
  isRead: __t.bool(),
});
export type DirectMessage = __Infer<typeof DirectMessage>;

export const DirectMessageConversation = __t.object("DirectMessageConversation", {
  id: __t.string(),
  user1: __t.identity(),
  user2: __t.identity(),
  lastMessageAt: __t.i64(),
  createdAt: __t.i64(),
});
export type DirectMessageConversation = __Infer<typeof DirectMessageConversation>;

export const EndRoundVote = __t.object("EndRoundVote", {
  id: __t.i32(),
  roomId: __t.i32(),
  userId: __t.string(),
  round: __t.i32(),
});
export type EndRoundVote = __Infer<typeof EndRoundVote>;

export const Equipment = __t.object("Equipment", {
  id: __t.i32(),
  roomId: __t.i32(),
  ownerId: __t.string(),
  equippedToUnitId: __t.option(__t.i32()),
  equipmentType: __t.string(),
  slot: __t.string(),
  itemName: __t.string(),
  tier: __t.i32(),
  material: __t.string(),
  enchantment: __t.option(__t.string()),
  quality: __t.string(),
  surface: __t.string(),
  attackBonus: __t.i32(),
  defenseBonus: __t.i32(),
  speedBonus: __t.i32(),
  healthBonus: __t.i32(),
  durability: __t.i32(),
  maxDurability: __t.i32(),
});
export type Equipment = __Infer<typeof Equipment>;

export const FriendRequest = __t.object("FriendRequest", {
  id: __t.i32(),
  fromUser: __t.identity(),
  toUser: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type FriendRequest = __Infer<typeof FriendRequest>;

export const Friendship = __t.object("Friendship", {
  id: __t.i32(),
  user1: __t.identity(),
  user2: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.string(),
  roomId: __t.string(),
  eventType: __t.string(),
  sourceId: __t.string(),
  targetId: __t.string(),
  value: __t.i32(),
  timestamp: __t.i64(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const GameRoom = __t.object("GameRoom", {
  id: __t.i32(),
  name: __t.string(),
  memberIds: __t.array(__t.string()),
  ticketIds: __t.array(__t.string()),
  offerIds: __t.array(__t.string()),
  startTime: __t.option(__t.i64()),
  currentRound: __t.i32(),
  buyinAmount: __t.f64(),
  potSize: __t.f64(),
  roundDuration: __t.i32(),
  gameStatus: __t.string(),
  eliminatedPlayers: __t.array(__t.string()),
  votesPerPlayer: __t.i32(),
  minPlayers: __t.i32(),
  maxPlayers: __t.option(__t.i32()),
  allowRebuy: __t.bool(),
  allowMidgameJoin: __t.bool(),
  combatEnabled: __t.bool(),
});
export type GameRoom = __Infer<typeof GameRoom>;

export const GameTickTimer = __t.object("GameTickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTickTimer = __Infer<typeof GameTickTimer>;

export const Guarantee = __t.object("Guarantee", {
  id: __t.i32(),
  roomId: __t.i32(),
  roundNumber: __t.i32(),
  voteId: __t.i32(),
  sellerId: __t.string(),
  color: __t.string(),
  price: __t.f64(),
  guaranteeType: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Guarantee = __Infer<typeof Guarantee>;

export const GuaranteePurchase = __t.object("GuaranteePurchase", {
  id: __t.i32(),
  guaranteeId: __t.i32(),
  buyerId: __t.string(),
  pricePaid: __t.f64(),
  timestamp: __t.timestamp(),
});
export type GuaranteePurchase = __Infer<typeof GuaranteePurchase>;

export const LaborerGenetics = __t.object("LaborerGenetics", {
  unitId: __t.i32(),
  generation: __t.i32(),
  parentAId: __t.option(__t.i32()),
  parentBId: __t.option(__t.i32()),
  combatIv: __t.i32(),
  gatheringIv: __t.i32(),
  craftingIv: __t.i32(),
  speedIv: __t.i32(),
  healthIv: __t.i32(),
  staminaIv: __t.i32(),
});
export type LaborerGenetics = __Infer<typeof LaborerGenetics>;

export const Message = __t.object("Message", {
  sender: __t.identity(),
  sent: __t.timestamp(),
  text: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const OwnedEquipment = __t.object("OwnedEquipment", {
  id: __t.i32(),
  ownerId: __t.string(),
  laborerId: __t.i32(),
  equipmentType: __t.string(),
  slot: __t.string(),
  itemName: __t.string(),
  tier: __t.i32(),
  material: __t.string(),
  enchantment: __t.option(__t.string()),
  quality: __t.string(),
  surface: __t.string(),
  attackBonus: __t.i32(),
  defenseBonus: __t.i32(),
  speedBonus: __t.i32(),
  healthBonus: __t.i32(),
  durability: __t.i32(),
  maxDurability: __t.i32(),
});
export type OwnedEquipment = __Infer<typeof OwnedEquipment>;

export const OwnedLaborer = __t.object("OwnedLaborer", {
  id: __t.i32(),
  ownerId: __t.string(),
  displayName: __t.string(),
  origin: __t.string(),
  woodcuttingXp: __t.i32(),
  woodcuttingLevel: __t.i32(),
  miningXp: __t.i32(),
  miningLevel: __t.i32(),
  foragingXp: __t.i32(),
  foragingLevel: __t.i32(),
  craftingXp: __t.i32(),
  craftingLevel: __t.i32(),
  sourceRoomId: __t.i32(),
  health: __t.i32(),
  maxHealth: __t.i32(),
  attack: __t.i32(),
  defense: __t.i32(),
  speed: __t.i32(),
});
export type OwnedLaborer = __Infer<typeof OwnedLaborer>;

export const PendingArenaResolve = __t.object("PendingArenaResolve", {
  roomId: __t.i32(),
  arenaId: __t.i32(),
  minorityColor: __t.string(),
  roundNumber: __t.i32(),
});
export type PendingArenaResolve = __Infer<typeof PendingArenaResolve>;

export const PlayerCurrency = __t.object("PlayerCurrency", {
  playerId: __t.string(),
  mtBalance: __t.f64(),
  mblsBalance: __t.f64(),
});
export type PlayerCurrency = __Infer<typeof PlayerCurrency>;

export const PlayerPosition = __t.object("PlayerPosition", {
  id: __t.i32(),
  identity: __t.identity(),
  roomId: __t.i32(),
  x: __t.f32(),
  z: __t.f32(),
  rotationY: __t.f32(),
  isMoving: __t.bool(),
});
export type PlayerPosition = __Infer<typeof PlayerPosition>;

export const PlayerStash = __t.object("PlayerStash", {
  playerId: __t.string(),
  wood: __t.i32(),
  stone: __t.i32(),
  metalOre: __t.i32(),
  coal: __t.i32(),
  gems: __t.i32(),
  fiber: __t.i32(),
  hide: __t.i32(),
  sand: __t.i32(),
  food: __t.i32(),
  woodenPole: __t.i32(),
  lumber: __t.i32(),
  cutStone: __t.i32(),
  metalIngot: __t.i32(),
  cloth: __t.i32(),
  rope: __t.i32(),
  leather: __t.i32(),
  glass: __t.i32(),
});
export type PlayerStash = __Infer<typeof PlayerStash>;

export const ReadyState = __t.object("ReadyState", {
  roomId: __t.string(),
  readyUserIds: __t.array(__t.string()),
  round: __t.i32(),
});
export type ReadyState = __Infer<typeof ReadyState>;

export const Resource = __t.object("Resource", {
  id: __t.string(),
  roomId: __t.i32(),
  resourceType: __t.string(),
  get position() {
    return Vector2;
  },
  amount: __t.i32(),
  maxAmount: __t.i32(),
  regenerationRate: __t.i32(),
  regenerationTimer: __t.i32(),
  depletionThreshold: __t.i32(),
});
export type Resource = __Infer<typeof Resource>;

export const RosterPick = __t.object("RosterPick", {
  id: __t.i32(),
  roomId: __t.i32(),
  playerId: __t.string(),
  laborerId: __t.i32(),
});
export type RosterPick = __Infer<typeof RosterPick>;

export const RoundTimerEntry = __t.object("RoundTimerEntry", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.i32(),
});
export type RoundTimerEntry = __Infer<typeof RoundTimerEntry>;

export const ServerNode = __t.object("ServerNode", {
  id: __t.i32(),
  name: __t.string(),
  serverType: __t.string(),
  parentId: __t.option(__t.i32()),
  tradingPeriodSeconds: __t.i64(),
  status: __t.string(),
  linkedRoomId: __t.option(__t.i32()),
  createdAt: __t.timestamp(),
});
export type ServerNode = __Infer<typeof ServerNode>;

export const SideBet = __t.object("SideBet", {
  id: __t.i32(),
  roomId: __t.i32(),
  roundNumber: __t.i32(),
  bettorId: __t.string(),
  betType: __t.string(),
  betTarget: __t.string(),
  amount: __t.f64(),
  payoutMultiplier: __t.f64(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type SideBet = __Infer<typeof SideBet>;

export const Spectator = __t.object("Spectator", {
  id: __t.i32(),
  roomId: __t.i32(),
  userId: __t.string(),
  joinedAt: __t.timestamp(),
});
export type Spectator = __Infer<typeof Spectator>;

export const Tournament = __t.object("Tournament", {
  id: __t.i32(),
  name: __t.string(),
  entryFee: __t.f64(),
  prizePool: __t.f64(),
  maxParticipants: __t.i32(),
  currentRound: __t.i32(),
  status: __t.string(),
  bracketType: __t.string(),
  roomIds: __t.array(__t.i32()),
  participantIds: __t.array(__t.string()),
  createdAt: __t.timestamp(),
});
export type Tournament = __Infer<typeof Tournament>;

export const TradeOffer = __t.object("TradeOffer", {
  id: __t.i32(),
  roomId: __t.i32(),
  roundNumber: __t.i32(),
  fromPlayer: __t.string(),
  offerType: __t.string(),
  voteId: __t.option(__t.i32()),
  price: __t.f64(),
  status: __t.string(),
  acceptedBy: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type TradeOffer = __Infer<typeof TradeOffer>;

export const Transaction = __t.object("Transaction", {
  id: __t.i32(),
  roomId: __t.i32(),
  fromPlayer: __t.string(),
  toPlayer: __t.string(),
  transactionType: __t.string(),
  amount: __t.f64(),
  voteId: __t.option(__t.i32()),
  guaranteeId: __t.option(__t.i32()),
  timestamp: __t.timestamp(),
});
export type Transaction = __Infer<typeof Transaction>;

export const Unit = __t.object("Unit", {
  id: __t.i32(),
  roomId: __t.i32(),
  ownerId: __t.string(),
  unitType: __t.string(),
  get position() {
    return Vector2;
  },
  get dimensions() {
    return Vector2;
  },
  fillStyle: __t.string(),
  taskType: __t.option(__t.string()),
  targetId: __t.option(__t.string()),
  voteColor: __t.option(__t.string()),
  voteGuarantee: __t.option(__t.string()),
  votePrice: __t.option(__t.i32()),
  voteOwner: __t.option(__t.string()),
  voteId: __t.option(__t.i32()),
  storageCapacity: __t.option(__t.i32()),
  isStorage: __t.bool(),
  buildingType: __t.option(__t.string()),
  constructionProgress: __t.option(__t.i32()),
  constructionMax: __t.option(__t.i32()),
  assignedUnitId: __t.option(__t.i32()),
  buildingRecipe: __t.option(__t.string()),
  taxRate: __t.option(__t.f32()),
  contributors: __t.array(__t.string()),
});
export type Unit = __Infer<typeof Unit>;

export const UnitInventory = __t.object("UnitInventory", {
  unitId: __t.i32(),
  wood: __t.i32(),
  stone: __t.i32(),
  metalOre: __t.i32(),
  coal: __t.i32(),
  gems: __t.i32(),
  fiber: __t.i32(),
  hide: __t.i32(),
  sand: __t.i32(),
  food: __t.i32(),
  woodenPole: __t.i32(),
  lumber: __t.i32(),
  cutStone: __t.i32(),
  metalIngot: __t.i32(),
  cloth: __t.i32(),
  rope: __t.i32(),
  leather: __t.i32(),
  glass: __t.i32(),
  maxCapacity: __t.i32(),
});
export type UnitInventory = __Infer<typeof UnitInventory>;

export const UnitStats = __t.object("UnitStats", {
  unitId: __t.i32(),
  health: __t.i32(),
  maxHealth: __t.i32(),
  attack: __t.i32(),
  defense: __t.i32(),
  speed: __t.i32(),
  gatherRate: __t.i32(),
  craftRate: __t.i32(),
  woodcuttingXp: __t.i32(),
  woodcuttingLevel: __t.i32(),
  miningXp: __t.i32(),
  miningLevel: __t.i32(),
  foragingXp: __t.i32(),
  foragingLevel: __t.i32(),
  craftingXp: __t.i32(),
  craftingLevel: __t.i32(),
  actionsRemaining: __t.i32(),
});
export type UnitStats = __Infer<typeof UnitStats>;

export const UnitTaskQueue = __t.object("UnitTaskQueue", {
  id: __t.i32(),
  unitId: __t.i32(),
  taskType: __t.string(),
  targetId: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
  completedAt: __t.option(__t.timestamp()),
});
export type UnitTaskQueue = __Infer<typeof UnitTaskQueue>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  walletBalance: __t.f64(),
  bankAccount: __t.f64(),
  totalProfitLoss: __t.f64(),
});
export type User = __Infer<typeof User>;

export const Vector2 = __t.object("Vector2", {
  x: __t.f32(),
  y: __t.f32(),
});
export type Vector2 = __Infer<typeof Vector2>;

export const Vote = __t.object("Vote", {
  id: __t.i32(),
  roomId: __t.i32(),
  roundNumber: __t.i32(),
  playerId: __t.string(),
  originalOwner: __t.string(),
  color: __t.option(__t.string()),
  isForSale: __t.bool(),
  salePrice: __t.option(__t.f64()),
  timestamp: __t.timestamp(),
});
export type Vote = __Infer<typeof Vote>;

