// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  unitId: __t.i32().primaryKey().name("unit_id"),
  health: __t.i32(),
  maxHealth: __t.i32().name("max_health"),
  attack: __t.i32(),
  defense: __t.i32(),
  speed: __t.i32(),
  gatherRate: __t.i32().name("gather_rate"),
  craftRate: __t.i32().name("craft_rate"),
});
