// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Vector2 as __Vector2 } from "./vector_2_type";

export type Unit = {
  id: number,
  roomId: number,
  ownerId: string,
  unitType: string,
  position: __Vector2,
  dimensions: __Vector2,
  fillStyle: string,
  taskType: string | undefined,
  targetId: string | undefined,
  voteColor: string | undefined,
  voteGuarantee: string | undefined,
  votePrice: number | undefined,
  voteOwner: string | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Unit {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("roomId", AlgebraicType.createI32Type()),
      new ProductTypeElement("ownerId", AlgebraicType.createStringType()),
      new ProductTypeElement("unitType", AlgebraicType.createStringType()),
      new ProductTypeElement("position", __Vector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("dimensions", __Vector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("fillStyle", AlgebraicType.createStringType()),
      new ProductTypeElement("taskType", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("targetId", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("voteColor", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("voteGuarantee", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("votePrice", AlgebraicType.createOptionType(AlgebraicType.createI32Type())),
      new ProductTypeElement("voteOwner", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Unit): void {
    Unit.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Unit {
    return Unit.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


