// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vector2,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  roomId: __t.i32().name("room_id"),
  ownerId: __t.string().name("owner_id"),
  unitType: __t.string().name("unit_type"),
  get position() {
    return Vector2;
  },
  get dimensions() {
    return Vector2;
  },
  fillStyle: __t.string().name("fill_style"),
  taskType: __t.option(__t.string()).name("task_type"),
  targetId: __t.option(__t.string()).name("target_id"),
  voteColor: __t.option(__t.string()).name("vote_color"),
  voteGuarantee: __t.option(__t.string()).name("vote_guarantee"),
  votePrice: __t.option(__t.i32()).name("vote_price"),
  voteOwner: __t.option(__t.string()).name("vote_owner"),
  voteId: __t.option(__t.i32()).name("vote_id"),
  storageCapacity: __t.option(__t.i32()).name("storage_capacity"),
  isStorage: __t.bool().name("is_storage"),
  buildingType: __t.option(__t.string()).name("building_type"),
  constructionProgress: __t.option(__t.i32()).name("construction_progress"),
  constructionMax: __t.option(__t.i32()).name("construction_max"),
  assignedUnitId: __t.option(__t.i32()).name("assigned_unit_id"),
  buildingRecipe: __t.option(__t.string()).name("building_recipe"),
  taxRate: __t.option(__t.f32()).name("tax_rate"),
  contributors: __t.array(__t.string()),
});
