// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  unitId: __t.i32().primaryKey().name("unit_id"),
  wood: __t.i32(),
  stone: __t.i32(),
  metalOre: __t.i32().name("metal_ore"),
  coal: __t.i32(),
  gems: __t.i32(),
  fiber: __t.i32(),
  hide: __t.i32(),
  sand: __t.i32(),
  food: __t.i32(),
  woodenPole: __t.i32().name("wooden_pole"),
  lumber: __t.i32(),
  cutStone: __t.i32().name("cut_stone"),
  metalIngot: __t.i32().name("metal_ingot"),
  cloth: __t.i32(),
  rope: __t.i32(),
  leather: __t.i32(),
  glass: __t.i32(),
  maxCapacity: __t.i32().name("max_capacity"),
});
