// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  roomId: __t.i32().name("room_id"),
  roundNumber: __t.i32().name("round_number"),
  playerId: __t.string().name("player_id"),
  originalOwner: __t.string().name("original_owner"),
  color: __t.option(__t.string()),
  isForSale: __t.bool().name("is_for_sale"),
  salePrice: __t.option(__t.f64()).name("sale_price"),
  timestamp: __t.timestamp(),
});
