// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "../accept_friend_request_reducer";
import AcceptTradeOfferReducer from "../accept_trade_offer_reducer";
import BlockUserReducer from "../block_user_reducer";
import CancelFriendRequestReducer from "../cancel_friend_request_reducer";
import CancelTradeOfferReducer from "../cancel_trade_offer_reducer";
import CancelUnitTaskReducer from "../cancel_unit_task_reducer";
import CreateChatRoomReducer from "../create_chat_room_reducer";
import CreateGameEventReducer from "../create_game_event_reducer";
import CreateGuaranteeReducer from "../create_guarantee_reducer";
import CreateRoomReducer from "../create_room_reducer";
import CreateStorageBuildingReducer from "../create_storage_building_reducer";
import CreateTradeOfferReducer from "../create_trade_offer_reducer";
import GatherResourceReducer from "../gather_resource_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import MarkMessagesReadReducer from "../mark_messages_read_reducer";
import MoveUnitReducer from "../move_unit_reducer";
import ProcessRoundVotesReducer from "../process_round_votes_reducer";
import PurchaseGuaranteeReducer from "../purchase_guarantee_reducer";
import QueueUnitTaskReducer from "../queue_unit_task_reducer";
import RebuyIntoGameReducer from "../rebuy_into_game_reducer";
import RejectFriendRequestReducer from "../reject_friend_request_reducer";
import RemoveFriendReducer from "../remove_friend_reducer";
import RemoveVoteFromSaleReducer from "../remove_vote_from_sale_reducer";
import ResetTestDataReducer from "../reset_test_data_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SendDirectMessageReducer from "../send_direct_message_reducer";
import SendFriendRequestReducer from "../send_friend_request_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetChatPermissionReducer from "../set_chat_permission_reducer";
import SetNameReducer from "../set_name_reducer";
import SetUnitTaskReducer from "../set_unit_task_reducer";
import SetUnitVoteColorReducer from "../set_unit_vote_color_reducer";
import SetVoteColorReducer from "../set_vote_color_reducer";
import SetVoteForSaleReducer from "../set_vote_for_sale_reducer";
import StartGameReducer from "../start_game_reducer";
import ToggleReadyReducer from "../toggle_ready_reducer";
import TradeUnitVoteReducer from "../trade_unit_vote_reducer";
import TransferResourcesReducer from "../transfer_resources_reducer";
import TransferToBankReducer from "../transfer_to_bank_reducer";
import TransferVoteOwnershipReducer from "../transfer_vote_ownership_reducer";
import UnblockUserReducer from "../unblock_user_reducer";
import UpgradeUnitReducer from "../upgrade_unit_reducer";
import WithdrawFromBankReducer from "../withdraw_from_bank_reducer";

export type AcceptFriendRequestParams = __Infer<typeof AcceptFriendRequestReducer>;
export type AcceptTradeOfferParams = __Infer<typeof AcceptTradeOfferReducer>;
export type BlockUserParams = __Infer<typeof BlockUserReducer>;
export type CancelFriendRequestParams = __Infer<typeof CancelFriendRequestReducer>;
export type CancelTradeOfferParams = __Infer<typeof CancelTradeOfferReducer>;
export type CancelUnitTaskParams = __Infer<typeof CancelUnitTaskReducer>;
export type CreateChatRoomParams = __Infer<typeof CreateChatRoomReducer>;
export type CreateGameEventParams = __Infer<typeof CreateGameEventReducer>;
export type CreateGuaranteeParams = __Infer<typeof CreateGuaranteeReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type CreateStorageBuildingParams = __Infer<typeof CreateStorageBuildingReducer>;
export type CreateTradeOfferParams = __Infer<typeof CreateTradeOfferReducer>;
export type GatherResourceParams = __Infer<typeof GatherResourceReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type MarkMessagesReadParams = __Infer<typeof MarkMessagesReadReducer>;
export type MoveUnitParams = __Infer<typeof MoveUnitReducer>;
export type ProcessRoundVotesParams = __Infer<typeof ProcessRoundVotesReducer>;
export type PurchaseGuaranteeParams = __Infer<typeof PurchaseGuaranteeReducer>;
export type QueueUnitTaskParams = __Infer<typeof QueueUnitTaskReducer>;
export type RebuyIntoGameParams = __Infer<typeof RebuyIntoGameReducer>;
export type RejectFriendRequestParams = __Infer<typeof RejectFriendRequestReducer>;
export type RemoveFriendParams = __Infer<typeof RemoveFriendReducer>;
export type RemoveVoteFromSaleParams = __Infer<typeof RemoveVoteFromSaleReducer>;
export type ResetTestDataParams = __Infer<typeof ResetTestDataReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SendDirectMessageParams = __Infer<typeof SendDirectMessageReducer>;
export type SendFriendRequestParams = __Infer<typeof SendFriendRequestReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetChatPermissionParams = __Infer<typeof SetChatPermissionReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetUnitTaskParams = __Infer<typeof SetUnitTaskReducer>;
export type SetUnitVoteColorParams = __Infer<typeof SetUnitVoteColorReducer>;
export type SetVoteColorParams = __Infer<typeof SetVoteColorReducer>;
export type SetVoteForSaleParams = __Infer<typeof SetVoteForSaleReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type ToggleReadyParams = __Infer<typeof ToggleReadyReducer>;
export type TradeUnitVoteParams = __Infer<typeof TradeUnitVoteReducer>;
export type TransferResourcesParams = __Infer<typeof TransferResourcesReducer>;
export type TransferToBankParams = __Infer<typeof TransferToBankReducer>;
export type TransferVoteOwnershipParams = __Infer<typeof TransferVoteOwnershipReducer>;
export type UnblockUserParams = __Infer<typeof UnblockUserReducer>;
export type UpgradeUnitParams = __Infer<typeof UpgradeUnitReducer>;
export type WithdrawFromBankParams = __Infer<typeof WithdrawFromBankReducer>;

