// These types will be automatically generated from the SpacetimeDB schema
// DO NOT EDIT THIS FILE MANUALLY

export type GameRoom = {
  id: string;
  name: string;
  member_ids: string[];
  ticket_ids: string[];
  offer_ids: string[];
  start_time: number | null;
  current_round: number;
};

export type Unit = {
  id: string;
  room_id: string;
  owner_id: string;
  type: "minion" | "target" | "structure";
  position: [number, number];
  dimensions: [number, number];
  fill_style: string;
  task_type: "gather" | "craft" | "upgrade" | null;
  target_id: string | null;
};

export type GameEvent = {
  id: string;
  room_id: string;
  type: "combat" | "resource" | "craft" | "upgrade";
  source_id: string;
  target_id: string;
  value: number;
  timestamp: number;
};

export type ReadyState = {
  room_id: string;
  ready_user_ids: string[];
  round: number;
};
