// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ChatPermission } from "./chat_permission_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `chat_permission`.
 *
 * Obtain a handle from the [`chatPermission`] property on [`RemoteTables`],
 * like `ctx.db.chatPermission`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.chatPermission.on_insert(...)`.
 */
export class ChatPermissionTableHandle {
  tableCache: TableCache<ChatPermission>;

  constructor(tableCache: TableCache<ChatPermission>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ChatPermission> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `roomId` unique index on the table `chat_permission`,
   * which allows point queries on the field of the same name
   * via the [`ChatPermissionRoomIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.chatPermission.roomId().find(...)`.
   *
   * Get a handle on the `roomId` unique index on the table `chat_permission`.
   */
  roomId = {
    // Find the subscribed row whose `roomId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): ChatPermission | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.roomId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ChatPermission) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ChatPermission) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ChatPermission) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ChatPermission) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ChatPermission, newRow: ChatPermission) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ChatPermission, newRow: ChatPermission) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
