// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type CreateGameEvent = {
  roomId: string,
  eventType: string,
  sourceId: string,
  targetId: string,
  value: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace CreateGameEvent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("roomId", AlgebraicType.createStringType()),
      new ProductTypeElement("eventType", AlgebraicType.createStringType()),
      new ProductTypeElement("sourceId", AlgebraicType.createStringType()),
      new ProductTypeElement("targetId", AlgebraicType.createStringType()),
      new ProductTypeElement("value", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: CreateGameEvent): void {
    CreateGameEvent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CreateGameEvent {
    return CreateGameEvent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

