// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type GuaranteePurchase = {
  id: number,
  guaranteeId: number,
  buyerId: string,
  pricePaid: number,
  timestamp: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GuaranteePurchase {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("guaranteeId", AlgebraicType.createI32Type()),
      new ProductTypeElement("buyerId", AlgebraicType.createStringType()),
      new ProductTypeElement("pricePaid", AlgebraicType.createF64Type()),
      new ProductTypeElement("timestamp", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GuaranteePurchase): void {
    GuaranteePurchase.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GuaranteePurchase {
    return GuaranteePurchase.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


