// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { CancelUnitTask } from "./cancel_unit_task_reducer.ts";
export { CancelUnitTask };
import { ClientConnected } from "./client_connected_reducer.ts";
export { ClientConnected };
import { CreateChatRoom } from "./create_chat_room_reducer.ts";
export { CreateChatRoom };
import { CreateGameEvent } from "./create_game_event_reducer.ts";
export { CreateGameEvent };
import { CreateGuarantee } from "./create_guarantee_reducer.ts";
export { CreateGuarantee };
import { CreateRoom } from "./create_room_reducer.ts";
export { CreateRoom };
import { CreateStorageBuilding } from "./create_storage_building_reducer.ts";
export { CreateStorageBuilding };
import { GameTick } from "./game_tick_reducer.ts";
export { GameTick };
import { GatherResource } from "./gather_resource_reducer.ts";
export { GatherResource };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { JoinRoom } from "./join_room_reducer.ts";
export { JoinRoom };
import { MoveUnit } from "./move_unit_reducer.ts";
export { MoveUnit };
import { ProcessRoundVotes } from "./process_round_votes_reducer.ts";
export { ProcessRoundVotes };
import { PurchaseGuarantee } from "./purchase_guarantee_reducer.ts";
export { PurchaseGuarantee };
import { QueueUnitTask } from "./queue_unit_task_reducer.ts";
export { QueueUnitTask };
import { SendChatMessage } from "./send_chat_message_reducer.ts";
export { SendChatMessage };
import { SendMessage } from "./send_message_reducer.ts";
export { SendMessage };
import { SetChatPermission } from "./set_chat_permission_reducer.ts";
export { SetChatPermission };
import { SetName } from "./set_name_reducer.ts";
export { SetName };
import { SetUnitTask } from "./set_unit_task_reducer.ts";
export { SetUnitTask };
import { SetUnitVoteColor } from "./set_unit_vote_color_reducer.ts";
export { SetUnitVoteColor };
import { SetVoteColor } from "./set_vote_color_reducer.ts";
export { SetVoteColor };
import { StartGame } from "./start_game_reducer.ts";
export { StartGame };
import { ToggleReady } from "./toggle_ready_reducer.ts";
export { ToggleReady };
import { TradeUnitVote } from "./trade_unit_vote_reducer.ts";
export { TradeUnitVote };
import { TransferResources } from "./transfer_resources_reducer.ts";
export { TransferResources };
import { TransferVoteOwnership } from "./transfer_vote_ownership_reducer.ts";
export { TransferVoteOwnership };
import { UpgradeUnit } from "./upgrade_unit_reducer.ts";
export { UpgradeUnit };

// Import and reexport all table handle types
import { ChatMessageTableHandle } from "./chat_message_table.ts";
export { ChatMessageTableHandle };
import { ChatPermissionTableHandle } from "./chat_permission_table.ts";
export { ChatPermissionTableHandle };
import { ChatRoomTableHandle } from "./chat_room_table.ts";
export { ChatRoomTableHandle };
import { GameEventTableHandle } from "./game_event_table.ts";
export { GameEventTableHandle };
import { GameRoomTableHandle } from "./game_room_table.ts";
export { GameRoomTableHandle };
import { GameTickTimerTableHandle } from "./game_tick_timer_table.ts";
export { GameTickTimerTableHandle };
import { GuaranteeTableHandle } from "./guarantee_table.ts";
export { GuaranteeTableHandle };
import { GuaranteePurchaseTableHandle } from "./guarantee_purchase_table.ts";
export { GuaranteePurchaseTableHandle };
import { MessageTableHandle } from "./message_table.ts";
export { MessageTableHandle };
import { ReadyStateTableHandle } from "./ready_state_table.ts";
export { ReadyStateTableHandle };
import { ResourceTableHandle } from "./resource_table.ts";
export { ResourceTableHandle };
import { TransactionTableHandle } from "./transaction_table.ts";
export { TransactionTableHandle };
import { UnitTableHandle } from "./unit_table.ts";
export { UnitTableHandle };
import { UnitInventoryTableHandle } from "./unit_inventory_table.ts";
export { UnitInventoryTableHandle };
import { UnitStatsTableHandle } from "./unit_stats_table.ts";
export { UnitStatsTableHandle };
import { UnitTaskQueueTableHandle } from "./unit_task_queue_table.ts";
export { UnitTaskQueueTableHandle };
import { UserTableHandle } from "./user_table.ts";
export { UserTableHandle };
import { VoteTableHandle } from "./vote_table.ts";
export { VoteTableHandle };

// Import and reexport all types
import { ChatMessage } from "./chat_message_type.ts";
export { ChatMessage };
import { ChatPermission } from "./chat_permission_type.ts";
export { ChatPermission };
import { ChatRoom } from "./chat_room_type.ts";
export { ChatRoom };
import { GameEvent } from "./game_event_type.ts";
export { GameEvent };
import { GameRoom } from "./game_room_type.ts";
export { GameRoom };
import { GameTickTimer } from "./game_tick_timer_type.ts";
export { GameTickTimer };
import { Guarantee } from "./guarantee_type.ts";
export { Guarantee };
import { GuaranteePurchase } from "./guarantee_purchase_type.ts";
export { GuaranteePurchase };
import { Message } from "./message_type.ts";
export { Message };
import { ReadyState } from "./ready_state_type.ts";
export { ReadyState };
import { Resource } from "./resource_type.ts";
export { Resource };
import { Transaction } from "./transaction_type.ts";
export { Transaction };
import { Unit } from "./unit_type.ts";
export { Unit };
import { UnitInventory } from "./unit_inventory_type.ts";
export { UnitInventory };
import { UnitStats } from "./unit_stats_type.ts";
export { UnitStats };
import { UnitTaskQueue } from "./unit_task_queue_type.ts";
export { UnitTaskQueue };
import { User } from "./user_type.ts";
export { User };
import { Vector2 } from "./vector_2_type.ts";
export { Vector2 };
import { Vote } from "./vote_type.ts";
export { Vote };

const REMOTE_MODULE = {
  tables: {
    chat_message: {
      tableName: "chat_message",
      rowType: ChatMessage.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    chat_permission: {
      tableName: "chat_permission",
      rowType: ChatPermission.getTypeScriptAlgebraicType(),
      primaryKey: "roomId",
    },
    chat_room: {
      tableName: "chat_room",
      rowType: ChatRoom.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    game_event: {
      tableName: "game_event",
      rowType: GameEvent.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    game_room: {
      tableName: "game_room",
      rowType: GameRoom.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    game_tick_timer: {
      tableName: "game_tick_timer",
      rowType: GameTickTimer.getTypeScriptAlgebraicType(),
      primaryKey: "scheduledId",
    },
    guarantee: {
      tableName: "guarantee",
      rowType: Guarantee.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    guarantee_purchase: {
      tableName: "guarantee_purchase",
      rowType: GuaranteePurchase.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    message: {
      tableName: "message",
      rowType: Message.getTypeScriptAlgebraicType(),
    },
    ready_state: {
      tableName: "ready_state",
      rowType: ReadyState.getTypeScriptAlgebraicType(),
      primaryKey: "roomId",
    },
    resource: {
      tableName: "resource",
      rowType: Resource.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    transaction: {
      tableName: "transaction",
      rowType: Transaction.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    unit: {
      tableName: "unit",
      rowType: Unit.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    unit_inventory: {
      tableName: "unit_inventory",
      rowType: UnitInventory.getTypeScriptAlgebraicType(),
      primaryKey: "unitId",
    },
    unit_stats: {
      tableName: "unit_stats",
      rowType: UnitStats.getTypeScriptAlgebraicType(),
      primaryKey: "unitId",
    },
    unit_task_queue: {
      tableName: "unit_task_queue",
      rowType: UnitTaskQueue.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    user: {
      tableName: "user",
      rowType: User.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
    },
    vote: {
      tableName: "vote",
      rowType: Vote.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
  },
  reducers: {
    cancel_unit_task: {
      reducerName: "cancel_unit_task",
      argsType: CancelUnitTask.getTypeScriptAlgebraicType(),
    },
    client_connected: {
      reducerName: "client_connected",
      argsType: ClientConnected.getTypeScriptAlgebraicType(),
    },
    create_chat_room: {
      reducerName: "create_chat_room",
      argsType: CreateChatRoom.getTypeScriptAlgebraicType(),
    },
    create_game_event: {
      reducerName: "create_game_event",
      argsType: CreateGameEvent.getTypeScriptAlgebraicType(),
    },
    create_guarantee: {
      reducerName: "create_guarantee",
      argsType: CreateGuarantee.getTypeScriptAlgebraicType(),
    },
    create_room: {
      reducerName: "create_room",
      argsType: CreateRoom.getTypeScriptAlgebraicType(),
    },
    create_storage_building: {
      reducerName: "create_storage_building",
      argsType: CreateStorageBuilding.getTypeScriptAlgebraicType(),
    },
    game_tick: {
      reducerName: "game_tick",
      argsType: GameTick.getTypeScriptAlgebraicType(),
    },
    gather_resource: {
      reducerName: "gather_resource",
      argsType: GatherResource.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    join_room: {
      reducerName: "join_room",
      argsType: JoinRoom.getTypeScriptAlgebraicType(),
    },
    move_unit: {
      reducerName: "move_unit",
      argsType: MoveUnit.getTypeScriptAlgebraicType(),
    },
    process_round_votes: {
      reducerName: "process_round_votes",
      argsType: ProcessRoundVotes.getTypeScriptAlgebraicType(),
    },
    purchase_guarantee: {
      reducerName: "purchase_guarantee",
      argsType: PurchaseGuarantee.getTypeScriptAlgebraicType(),
    },
    queue_unit_task: {
      reducerName: "queue_unit_task",
      argsType: QueueUnitTask.getTypeScriptAlgebraicType(),
    },
    send_chat_message: {
      reducerName: "send_chat_message",
      argsType: SendChatMessage.getTypeScriptAlgebraicType(),
    },
    send_message: {
      reducerName: "send_message",
      argsType: SendMessage.getTypeScriptAlgebraicType(),
    },
    set_chat_permission: {
      reducerName: "set_chat_permission",
      argsType: SetChatPermission.getTypeScriptAlgebraicType(),
    },
    set_name: {
      reducerName: "set_name",
      argsType: SetName.getTypeScriptAlgebraicType(),
    },
    set_unit_task: {
      reducerName: "set_unit_task",
      argsType: SetUnitTask.getTypeScriptAlgebraicType(),
    },
    set_unit_vote_color: {
      reducerName: "set_unit_vote_color",
      argsType: SetUnitVoteColor.getTypeScriptAlgebraicType(),
    },
    set_vote_color: {
      reducerName: "set_vote_color",
      argsType: SetVoteColor.getTypeScriptAlgebraicType(),
    },
    start_game: {
      reducerName: "start_game",
      argsType: StartGame.getTypeScriptAlgebraicType(),
    },
    toggle_ready: {
      reducerName: "toggle_ready",
      argsType: ToggleReady.getTypeScriptAlgebraicType(),
    },
    trade_unit_vote: {
      reducerName: "trade_unit_vote",
      argsType: TradeUnitVote.getTypeScriptAlgebraicType(),
    },
    transfer_resources: {
      reducerName: "transfer_resources",
      argsType: TransferResources.getTypeScriptAlgebraicType(),
    },
    transfer_vote_ownership: {
      reducerName: "transfer_vote_ownership",
      argsType: TransferVoteOwnership.getTypeScriptAlgebraicType(),
    },
    upgrade_unit: {
      reducerName: "upgrade_unit",
      argsType: UpgradeUnit.getTypeScriptAlgebraicType(),
    },
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CancelUnitTask", args: CancelUnitTask }
| { name: "ClientConnected", args: ClientConnected }
| { name: "CreateChatRoom", args: CreateChatRoom }
| { name: "CreateGameEvent", args: CreateGameEvent }
| { name: "CreateGuarantee", args: CreateGuarantee }
| { name: "CreateRoom", args: CreateRoom }
| { name: "CreateStorageBuilding", args: CreateStorageBuilding }
| { name: "GameTick", args: GameTick }
| { name: "GatherResource", args: GatherResource }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "JoinRoom", args: JoinRoom }
| { name: "MoveUnit", args: MoveUnit }
| { name: "ProcessRoundVotes", args: ProcessRoundVotes }
| { name: "PurchaseGuarantee", args: PurchaseGuarantee }
| { name: "QueueUnitTask", args: QueueUnitTask }
| { name: "SendChatMessage", args: SendChatMessage }
| { name: "SendMessage", args: SendMessage }
| { name: "SetChatPermission", args: SetChatPermission }
| { name: "SetName", args: SetName }
| { name: "SetUnitTask", args: SetUnitTask }
| { name: "SetUnitVoteColor", args: SetUnitVoteColor }
| { name: "SetVoteColor", args: SetVoteColor }
| { name: "StartGame", args: StartGame }
| { name: "ToggleReady", args: ToggleReady }
| { name: "TradeUnitVote", args: TradeUnitVote }
| { name: "TransferResources", args: TransferResources }
| { name: "TransferVoteOwnership", args: TransferVoteOwnership }
| { name: "UpgradeUnit", args: UpgradeUnit }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  cancelUnitTask(taskId: number) {
    const __args = { taskId };
    let __writer = new BinaryWriter(1024);
    CancelUnitTask.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("cancel_unit_task", __argsBuffer, this.setCallReducerFlags.cancelUnitTaskFlags);
  }

  onCancelUnitTask(callback: (ctx: ReducerEventContext, taskId: number) => void) {
    this.connection.onReducer("cancel_unit_task", callback);
  }

  removeOnCancelUnitTask(callback: (ctx: ReducerEventContext, taskId: number) => void) {
    this.connection.offReducer("cancel_unit_task", callback);
  }

  onClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_connected", callback);
  }

  removeOnClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_connected", callback);
  }

  createChatRoom(name: string) {
    const __args = { name };
    let __writer = new BinaryWriter(1024);
    CreateChatRoom.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_chat_room", __argsBuffer, this.setCallReducerFlags.createChatRoomFlags);
  }

  onCreateChatRoom(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.onReducer("create_chat_room", callback);
  }

  removeOnCreateChatRoom(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.offReducer("create_chat_room", callback);
  }

  createGameEvent(roomId: string, eventType: string, sourceId: string, targetId: string, value: number) {
    const __args = { roomId, eventType, sourceId, targetId, value };
    let __writer = new BinaryWriter(1024);
    CreateGameEvent.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_game_event", __argsBuffer, this.setCallReducerFlags.createGameEventFlags);
  }

  onCreateGameEvent(callback: (ctx: ReducerEventContext, roomId: string, eventType: string, sourceId: string, targetId: string, value: number) => void) {
    this.connection.onReducer("create_game_event", callback);
  }

  removeOnCreateGameEvent(callback: (ctx: ReducerEventContext, roomId: string, eventType: string, sourceId: string, targetId: string, value: number) => void) {
    this.connection.offReducer("create_game_event", callback);
  }

  createGuarantee(roomId: number, roundNumber: number, color: string, price: number, guaranteeType: string) {
    const __args = { roomId, roundNumber, color, price, guaranteeType };
    let __writer = new BinaryWriter(1024);
    CreateGuarantee.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_guarantee", __argsBuffer, this.setCallReducerFlags.createGuaranteeFlags);
  }

  onCreateGuarantee(callback: (ctx: ReducerEventContext, roomId: number, roundNumber: number, color: string, price: number, guaranteeType: string) => void) {
    this.connection.onReducer("create_guarantee", callback);
  }

  removeOnCreateGuarantee(callback: (ctx: ReducerEventContext, roomId: number, roundNumber: number, color: string, price: number, guaranteeType: string) => void) {
    this.connection.offReducer("create_guarantee", callback);
  }

  createRoom(roomId: string, name: string, creatorId: string, buyinAmount: number) {
    const __args = { roomId, name, creatorId, buyinAmount };
    let __writer = new BinaryWriter(1024);
    CreateRoom.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_room", __argsBuffer, this.setCallReducerFlags.createRoomFlags);
  }

  onCreateRoom(callback: (ctx: ReducerEventContext, roomId: string, name: string, creatorId: string, buyinAmount: number) => void) {
    this.connection.onReducer("create_room", callback);
  }

  removeOnCreateRoom(callback: (ctx: ReducerEventContext, roomId: string, name: string, creatorId: string, buyinAmount: number) => void) {
    this.connection.offReducer("create_room", callback);
  }

  createStorageBuilding(roomId: number, position: Vector2, capacity: number) {
    const __args = { roomId, position, capacity };
    let __writer = new BinaryWriter(1024);
    CreateStorageBuilding.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_storage_building", __argsBuffer, this.setCallReducerFlags.createStorageBuildingFlags);
  }

  onCreateStorageBuilding(callback: (ctx: ReducerEventContext, roomId: number, position: Vector2, capacity: number) => void) {
    this.connection.onReducer("create_storage_building", callback);
  }

  removeOnCreateStorageBuilding(callback: (ctx: ReducerEventContext, roomId: number, position: Vector2, capacity: number) => void) {
    this.connection.offReducer("create_storage_building", callback);
  }

  gameTick(timer: GameTickTimer) {
    const __args = { timer };
    let __writer = new BinaryWriter(1024);
    GameTick.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("game_tick", __argsBuffer, this.setCallReducerFlags.gameTickFlags);
  }

  onGameTick(callback: (ctx: ReducerEventContext, timer: GameTickTimer) => void) {
    this.connection.onReducer("game_tick", callback);
  }

  removeOnGameTick(callback: (ctx: ReducerEventContext, timer: GameTickTimer) => void) {
    this.connection.offReducer("game_tick", callback);
  }

  gatherResource(unitId: number, resourceId: string) {
    const __args = { unitId, resourceId };
    let __writer = new BinaryWriter(1024);
    GatherResource.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("gather_resource", __argsBuffer, this.setCallReducerFlags.gatherResourceFlags);
  }

  onGatherResource(callback: (ctx: ReducerEventContext, unitId: number, resourceId: string) => void) {
    this.connection.onReducer("gather_resource", callback);
  }

  removeOnGatherResource(callback: (ctx: ReducerEventContext, unitId: number, resourceId: string) => void) {
    this.connection.offReducer("gather_resource", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  joinRoom(roomId: number, userId: string) {
    const __args = { roomId, userId };
    let __writer = new BinaryWriter(1024);
    JoinRoom.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("join_room", __argsBuffer, this.setCallReducerFlags.joinRoomFlags);
  }

  onJoinRoom(callback: (ctx: ReducerEventContext, roomId: number, userId: string) => void) {
    this.connection.onReducer("join_room", callback);
  }

  removeOnJoinRoom(callback: (ctx: ReducerEventContext, roomId: number, userId: string) => void) {
    this.connection.offReducer("join_room", callback);
  }

  moveUnit(unitId: number, targetPosition: Vector2) {
    const __args = { unitId, targetPosition };
    let __writer = new BinaryWriter(1024);
    MoveUnit.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("move_unit", __argsBuffer, this.setCallReducerFlags.moveUnitFlags);
  }

  onMoveUnit(callback: (ctx: ReducerEventContext, unitId: number, targetPosition: Vector2) => void) {
    this.connection.onReducer("move_unit", callback);
  }

  removeOnMoveUnit(callback: (ctx: ReducerEventContext, unitId: number, targetPosition: Vector2) => void) {
    this.connection.offReducer("move_unit", callback);
  }

  processRoundVotes(roomId: number, roundNumber: number) {
    const __args = { roomId, roundNumber };
    let __writer = new BinaryWriter(1024);
    ProcessRoundVotes.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("process_round_votes", __argsBuffer, this.setCallReducerFlags.processRoundVotesFlags);
  }

  onProcessRoundVotes(callback: (ctx: ReducerEventContext, roomId: number, roundNumber: number) => void) {
    this.connection.onReducer("process_round_votes", callback);
  }

  removeOnProcessRoundVotes(callback: (ctx: ReducerEventContext, roomId: number, roundNumber: number) => void) {
    this.connection.offReducer("process_round_votes", callback);
  }

  purchaseGuarantee(guaranteeId: number) {
    const __args = { guaranteeId };
    let __writer = new BinaryWriter(1024);
    PurchaseGuarantee.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("purchase_guarantee", __argsBuffer, this.setCallReducerFlags.purchaseGuaranteeFlags);
  }

  onPurchaseGuarantee(callback: (ctx: ReducerEventContext, guaranteeId: number) => void) {
    this.connection.onReducer("purchase_guarantee", callback);
  }

  removeOnPurchaseGuarantee(callback: (ctx: ReducerEventContext, guaranteeId: number) => void) {
    this.connection.offReducer("purchase_guarantee", callback);
  }

  queueUnitTask(unitId: number, taskType: string, targetId: string) {
    const __args = { unitId, taskType, targetId };
    let __writer = new BinaryWriter(1024);
    QueueUnitTask.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("queue_unit_task", __argsBuffer, this.setCallReducerFlags.queueUnitTaskFlags);
  }

  onQueueUnitTask(callback: (ctx: ReducerEventContext, unitId: number, taskType: string, targetId: string) => void) {
    this.connection.onReducer("queue_unit_task", callback);
  }

  removeOnQueueUnitTask(callback: (ctx: ReducerEventContext, unitId: number, taskType: string, targetId: string) => void) {
    this.connection.offReducer("queue_unit_task", callback);
  }

  sendChatMessage(roomId: string, text: string, roundNumber: number | undefined) {
    const __args = { roomId, text, roundNumber };
    let __writer = new BinaryWriter(1024);
    SendChatMessage.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("send_chat_message", __argsBuffer, this.setCallReducerFlags.sendChatMessageFlags);
  }

  onSendChatMessage(callback: (ctx: ReducerEventContext, roomId: string, text: string, roundNumber: number | undefined) => void) {
    this.connection.onReducer("send_chat_message", callback);
  }

  removeOnSendChatMessage(callback: (ctx: ReducerEventContext, roomId: string, text: string, roundNumber: number | undefined) => void) {
    this.connection.offReducer("send_chat_message", callback);
  }

  sendMessage(text: string) {
    const __args = { text };
    let __writer = new BinaryWriter(1024);
    SendMessage.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("send_message", __argsBuffer, this.setCallReducerFlags.sendMessageFlags);
  }

  onSendMessage(callback: (ctx: ReducerEventContext, text: string) => void) {
    this.connection.onReducer("send_message", callback);
  }

  removeOnSendMessage(callback: (ctx: ReducerEventContext, text: string) => void) {
    this.connection.offReducer("send_message", callback);
  }

  setChatPermission(roomId: string, userId: Identity, permission: string) {
    const __args = { roomId, userId, permission };
    let __writer = new BinaryWriter(1024);
    SetChatPermission.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_chat_permission", __argsBuffer, this.setCallReducerFlags.setChatPermissionFlags);
  }

  onSetChatPermission(callback: (ctx: ReducerEventContext, roomId: string, userId: Identity, permission: string) => void) {
    this.connection.onReducer("set_chat_permission", callback);
  }

  removeOnSetChatPermission(callback: (ctx: ReducerEventContext, roomId: string, userId: Identity, permission: string) => void) {
    this.connection.offReducer("set_chat_permission", callback);
  }

  setName(name: string) {
    const __args = { name };
    let __writer = new BinaryWriter(1024);
    SetName.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_name", __argsBuffer, this.setCallReducerFlags.setNameFlags);
  }

  onSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.onReducer("set_name", callback);
  }

  removeOnSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.offReducer("set_name", callback);
  }

  setUnitTask(unitId: number, taskType: string, targetId: string) {
    const __args = { unitId, taskType, targetId };
    let __writer = new BinaryWriter(1024);
    SetUnitTask.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_unit_task", __argsBuffer, this.setCallReducerFlags.setUnitTaskFlags);
  }

  onSetUnitTask(callback: (ctx: ReducerEventContext, unitId: number, taskType: string, targetId: string) => void) {
    this.connection.onReducer("set_unit_task", callback);
  }

  removeOnSetUnitTask(callback: (ctx: ReducerEventContext, unitId: number, taskType: string, targetId: string) => void) {
    this.connection.offReducer("set_unit_task", callback);
  }

  setUnitVoteColor(unitId: number, color: string) {
    const __args = { unitId, color };
    let __writer = new BinaryWriter(1024);
    SetUnitVoteColor.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_unit_vote_color", __argsBuffer, this.setCallReducerFlags.setUnitVoteColorFlags);
  }

  onSetUnitVoteColor(callback: (ctx: ReducerEventContext, unitId: number, color: string) => void) {
    this.connection.onReducer("set_unit_vote_color", callback);
  }

  removeOnSetUnitVoteColor(callback: (ctx: ReducerEventContext, unitId: number, color: string) => void) {
    this.connection.offReducer("set_unit_vote_color", callback);
  }

  setVoteColor(voteId: number, color: string) {
    const __args = { voteId, color };
    let __writer = new BinaryWriter(1024);
    SetVoteColor.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_vote_color", __argsBuffer, this.setCallReducerFlags.setVoteColorFlags);
  }

  onSetVoteColor(callback: (ctx: ReducerEventContext, voteId: number, color: string) => void) {
    this.connection.onReducer("set_vote_color", callback);
  }

  removeOnSetVoteColor(callback: (ctx: ReducerEventContext, voteId: number, color: string) => void) {
    this.connection.offReducer("set_vote_color", callback);
  }

  startGame(roomId: number) {
    const __args = { roomId };
    let __writer = new BinaryWriter(1024);
    StartGame.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("start_game", __argsBuffer, this.setCallReducerFlags.startGameFlags);
  }

  onStartGame(callback: (ctx: ReducerEventContext, roomId: number) => void) {
    this.connection.onReducer("start_game", callback);
  }

  removeOnStartGame(callback: (ctx: ReducerEventContext, roomId: number) => void) {
    this.connection.offReducer("start_game", callback);
  }

  toggleReady(roomId: number, userId: string) {
    const __args = { roomId, userId };
    let __writer = new BinaryWriter(1024);
    ToggleReady.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("toggle_ready", __argsBuffer, this.setCallReducerFlags.toggleReadyFlags);
  }

  onToggleReady(callback: (ctx: ReducerEventContext, roomId: number, userId: string) => void) {
    this.connection.onReducer("toggle_ready", callback);
  }

  removeOnToggleReady(callback: (ctx: ReducerEventContext, roomId: number, userId: string) => void) {
    this.connection.offReducer("toggle_ready", callback);
  }

  tradeUnitVote(unitId: number, buyerId: string, price: number) {
    const __args = { unitId, buyerId, price };
    let __writer = new BinaryWriter(1024);
    TradeUnitVote.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("trade_unit_vote", __argsBuffer, this.setCallReducerFlags.tradeUnitVoteFlags);
  }

  onTradeUnitVote(callback: (ctx: ReducerEventContext, unitId: number, buyerId: string, price: number) => void) {
    this.connection.onReducer("trade_unit_vote", callback);
  }

  removeOnTradeUnitVote(callback: (ctx: ReducerEventContext, unitId: number, buyerId: string, price: number) => void) {
    this.connection.offReducer("trade_unit_vote", callback);
  }

  transferResources(sourceId: number, targetId: number, resourceType: string, amount: number) {
    const __args = { sourceId, targetId, resourceType, amount };
    let __writer = new BinaryWriter(1024);
    TransferResources.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("transfer_resources", __argsBuffer, this.setCallReducerFlags.transferResourcesFlags);
  }

  onTransferResources(callback: (ctx: ReducerEventContext, sourceId: number, targetId: number, resourceType: string, amount: number) => void) {
    this.connection.onReducer("transfer_resources", callback);
  }

  removeOnTransferResources(callback: (ctx: ReducerEventContext, sourceId: number, targetId: number, resourceType: string, amount: number) => void) {
    this.connection.offReducer("transfer_resources", callback);
  }

  transferVoteOwnership(voteId: number, buyerId: string, price: number) {
    const __args = { voteId, buyerId, price };
    let __writer = new BinaryWriter(1024);
    TransferVoteOwnership.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("transfer_vote_ownership", __argsBuffer, this.setCallReducerFlags.transferVoteOwnershipFlags);
  }

  onTransferVoteOwnership(callback: (ctx: ReducerEventContext, voteId: number, buyerId: string, price: number) => void) {
    this.connection.onReducer("transfer_vote_ownership", callback);
  }

  removeOnTransferVoteOwnership(callback: (ctx: ReducerEventContext, voteId: number, buyerId: string, price: number) => void) {
    this.connection.offReducer("transfer_vote_ownership", callback);
  }

  upgradeUnit(unitId: number, upgradeType: string) {
    const __args = { unitId, upgradeType };
    let __writer = new BinaryWriter(1024);
    UpgradeUnit.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("upgrade_unit", __argsBuffer, this.setCallReducerFlags.upgradeUnitFlags);
  }

  onUpgradeUnit(callback: (ctx: ReducerEventContext, unitId: number, upgradeType: string) => void) {
    this.connection.onReducer("upgrade_unit", callback);
  }

  removeOnUpgradeUnit(callback: (ctx: ReducerEventContext, unitId: number, upgradeType: string) => void) {
    this.connection.offReducer("upgrade_unit", callback);
  }

}

export class SetReducerFlags {
  cancelUnitTaskFlags: CallReducerFlags = 'FullUpdate';
  cancelUnitTask(flags: CallReducerFlags) {
    this.cancelUnitTaskFlags = flags;
  }

  createChatRoomFlags: CallReducerFlags = 'FullUpdate';
  createChatRoom(flags: CallReducerFlags) {
    this.createChatRoomFlags = flags;
  }

  createGameEventFlags: CallReducerFlags = 'FullUpdate';
  createGameEvent(flags: CallReducerFlags) {
    this.createGameEventFlags = flags;
  }

  createGuaranteeFlags: CallReducerFlags = 'FullUpdate';
  createGuarantee(flags: CallReducerFlags) {
    this.createGuaranteeFlags = flags;
  }

  createRoomFlags: CallReducerFlags = 'FullUpdate';
  createRoom(flags: CallReducerFlags) {
    this.createRoomFlags = flags;
  }

  createStorageBuildingFlags: CallReducerFlags = 'FullUpdate';
  createStorageBuilding(flags: CallReducerFlags) {
    this.createStorageBuildingFlags = flags;
  }

  gameTickFlags: CallReducerFlags = 'FullUpdate';
  gameTick(flags: CallReducerFlags) {
    this.gameTickFlags = flags;
  }

  gatherResourceFlags: CallReducerFlags = 'FullUpdate';
  gatherResource(flags: CallReducerFlags) {
    this.gatherResourceFlags = flags;
  }

  joinRoomFlags: CallReducerFlags = 'FullUpdate';
  joinRoom(flags: CallReducerFlags) {
    this.joinRoomFlags = flags;
  }

  moveUnitFlags: CallReducerFlags = 'FullUpdate';
  moveUnit(flags: CallReducerFlags) {
    this.moveUnitFlags = flags;
  }

  processRoundVotesFlags: CallReducerFlags = 'FullUpdate';
  processRoundVotes(flags: CallReducerFlags) {
    this.processRoundVotesFlags = flags;
  }

  purchaseGuaranteeFlags: CallReducerFlags = 'FullUpdate';
  purchaseGuarantee(flags: CallReducerFlags) {
    this.purchaseGuaranteeFlags = flags;
  }

  queueUnitTaskFlags: CallReducerFlags = 'FullUpdate';
  queueUnitTask(flags: CallReducerFlags) {
    this.queueUnitTaskFlags = flags;
  }

  sendChatMessageFlags: CallReducerFlags = 'FullUpdate';
  sendChatMessage(flags: CallReducerFlags) {
    this.sendChatMessageFlags = flags;
  }

  sendMessageFlags: CallReducerFlags = 'FullUpdate';
  sendMessage(flags: CallReducerFlags) {
    this.sendMessageFlags = flags;
  }

  setChatPermissionFlags: CallReducerFlags = 'FullUpdate';
  setChatPermission(flags: CallReducerFlags) {
    this.setChatPermissionFlags = flags;
  }

  setNameFlags: CallReducerFlags = 'FullUpdate';
  setName(flags: CallReducerFlags) {
    this.setNameFlags = flags;
  }

  setUnitTaskFlags: CallReducerFlags = 'FullUpdate';
  setUnitTask(flags: CallReducerFlags) {
    this.setUnitTaskFlags = flags;
  }

  setUnitVoteColorFlags: CallReducerFlags = 'FullUpdate';
  setUnitVoteColor(flags: CallReducerFlags) {
    this.setUnitVoteColorFlags = flags;
  }

  setVoteColorFlags: CallReducerFlags = 'FullUpdate';
  setVoteColor(flags: CallReducerFlags) {
    this.setVoteColorFlags = flags;
  }

  startGameFlags: CallReducerFlags = 'FullUpdate';
  startGame(flags: CallReducerFlags) {
    this.startGameFlags = flags;
  }

  toggleReadyFlags: CallReducerFlags = 'FullUpdate';
  toggleReady(flags: CallReducerFlags) {
    this.toggleReadyFlags = flags;
  }

  tradeUnitVoteFlags: CallReducerFlags = 'FullUpdate';
  tradeUnitVote(flags: CallReducerFlags) {
    this.tradeUnitVoteFlags = flags;
  }

  transferResourcesFlags: CallReducerFlags = 'FullUpdate';
  transferResources(flags: CallReducerFlags) {
    this.transferResourcesFlags = flags;
  }

  transferVoteOwnershipFlags: CallReducerFlags = 'FullUpdate';
  transferVoteOwnership(flags: CallReducerFlags) {
    this.transferVoteOwnershipFlags = flags;
  }

  upgradeUnitFlags: CallReducerFlags = 'FullUpdate';
  upgradeUnit(flags: CallReducerFlags) {
    this.upgradeUnitFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get chatMessage(): ChatMessageTableHandle {
    return new ChatMessageTableHandle(this.connection.clientCache.getOrCreateTable<ChatMessage>(REMOTE_MODULE.tables.chat_message));
  }

  get chatPermission(): ChatPermissionTableHandle {
    return new ChatPermissionTableHandle(this.connection.clientCache.getOrCreateTable<ChatPermission>(REMOTE_MODULE.tables.chat_permission));
  }

  get chatRoom(): ChatRoomTableHandle {
    return new ChatRoomTableHandle(this.connection.clientCache.getOrCreateTable<ChatRoom>(REMOTE_MODULE.tables.chat_room));
  }

  get gameEvent(): GameEventTableHandle {
    return new GameEventTableHandle(this.connection.clientCache.getOrCreateTable<GameEvent>(REMOTE_MODULE.tables.game_event));
  }

  get gameRoom(): GameRoomTableHandle {
    return new GameRoomTableHandle(this.connection.clientCache.getOrCreateTable<GameRoom>(REMOTE_MODULE.tables.game_room));
  }

  get gameTickTimer(): GameTickTimerTableHandle {
    return new GameTickTimerTableHandle(this.connection.clientCache.getOrCreateTable<GameTickTimer>(REMOTE_MODULE.tables.game_tick_timer));
  }

  get guarantee(): GuaranteeTableHandle {
    return new GuaranteeTableHandle(this.connection.clientCache.getOrCreateTable<Guarantee>(REMOTE_MODULE.tables.guarantee));
  }

  get guaranteePurchase(): GuaranteePurchaseTableHandle {
    return new GuaranteePurchaseTableHandle(this.connection.clientCache.getOrCreateTable<GuaranteePurchase>(REMOTE_MODULE.tables.guarantee_purchase));
  }

  get message(): MessageTableHandle {
    return new MessageTableHandle(this.connection.clientCache.getOrCreateTable<Message>(REMOTE_MODULE.tables.message));
  }

  get readyState(): ReadyStateTableHandle {
    return new ReadyStateTableHandle(this.connection.clientCache.getOrCreateTable<ReadyState>(REMOTE_MODULE.tables.ready_state));
  }

  get resource(): ResourceTableHandle {
    return new ResourceTableHandle(this.connection.clientCache.getOrCreateTable<Resource>(REMOTE_MODULE.tables.resource));
  }

  get transaction(): TransactionTableHandle {
    return new TransactionTableHandle(this.connection.clientCache.getOrCreateTable<Transaction>(REMOTE_MODULE.tables.transaction));
  }

  get unit(): UnitTableHandle {
    return new UnitTableHandle(this.connection.clientCache.getOrCreateTable<Unit>(REMOTE_MODULE.tables.unit));
  }

  get unitInventory(): UnitInventoryTableHandle {
    return new UnitInventoryTableHandle(this.connection.clientCache.getOrCreateTable<UnitInventory>(REMOTE_MODULE.tables.unit_inventory));
  }

  get unitStats(): UnitStatsTableHandle {
    return new UnitStatsTableHandle(this.connection.clientCache.getOrCreateTable<UnitStats>(REMOTE_MODULE.tables.unit_stats));
  }

  get unitTaskQueue(): UnitTaskQueueTableHandle {
    return new UnitTaskQueueTableHandle(this.connection.clientCache.getOrCreateTable<UnitTaskQueue>(REMOTE_MODULE.tables.unit_task_queue));
  }

  get user(): UserTableHandle {
    return new UserTableHandle(this.connection.clientCache.getOrCreateTable<User>(REMOTE_MODULE.tables.user));
  }

  get vote(): VoteTableHandle {
    return new VoteTableHandle(this.connection.clientCache.getOrCreateTable<Vote>(REMOTE_MODULE.tables.vote));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
