// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type UnitStats = {
  unitId: number,
  health: number,
  maxHealth: number,
  attack: number,
  defense: number,
  speed: number,
  gatherRate: number,
  craftRate: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UnitStats {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("unitId", AlgebraicType.createI32Type()),
      new ProductTypeElement("health", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxHealth", AlgebraicType.createI32Type()),
      new ProductTypeElement("attack", AlgebraicType.createI32Type()),
      new ProductTypeElement("defense", AlgebraicType.createI32Type()),
      new ProductTypeElement("speed", AlgebraicType.createI32Type()),
      new ProductTypeElement("gatherRate", AlgebraicType.createI32Type()),
      new ProductTypeElement("craftRate", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UnitStats): void {
    UnitStats.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UnitStats {
    return UnitStats.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


