// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type UnitInventory = {
  unitId: number,
  wood: number,
  stone: number,
  metalOre: number,
  coal: number,
  gems: number,
  fiber: number,
  hide: number,
  sand: number,
  food: number,
  woodenPole: number,
  lumber: number,
  cutStone: number,
  metalIngot: number,
  cloth: number,
  rope: number,
  leather: number,
  glass: number,
  maxCapacity: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UnitInventory {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("unitId", AlgebraicType.createI32Type()),
      new ProductTypeElement("wood", AlgebraicType.createI32Type()),
      new ProductTypeElement("stone", AlgebraicType.createI32Type()),
      new ProductTypeElement("metalOre", AlgebraicType.createI32Type()),
      new ProductTypeElement("coal", AlgebraicType.createI32Type()),
      new ProductTypeElement("gems", AlgebraicType.createI32Type()),
      new ProductTypeElement("fiber", AlgebraicType.createI32Type()),
      new ProductTypeElement("hide", AlgebraicType.createI32Type()),
      new ProductTypeElement("sand", AlgebraicType.createI32Type()),
      new ProductTypeElement("food", AlgebraicType.createI32Type()),
      new ProductTypeElement("woodenPole", AlgebraicType.createI32Type()),
      new ProductTypeElement("lumber", AlgebraicType.createI32Type()),
      new ProductTypeElement("cutStone", AlgebraicType.createI32Type()),
      new ProductTypeElement("metalIngot", AlgebraicType.createI32Type()),
      new ProductTypeElement("cloth", AlgebraicType.createI32Type()),
      new ProductTypeElement("rope", AlgebraicType.createI32Type()),
      new ProductTypeElement("leather", AlgebraicType.createI32Type()),
      new ProductTypeElement("glass", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxCapacity", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UnitInventory): void {
    UnitInventory.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UnitInventory {
    return UnitInventory.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


